name: Docker Build, Run, and Push

on:
  push:
    branches:
      - main

jobs:
  build-run-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run Docker container
      run: |
        docker build -t my-anagram-app .
        docker run my-anagram-app

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: docker tag my-anagram-app ${{ secrets.DOCKER_USERNAME }}/my-anagram-app:latest

    - name: Push Docker image to registry
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-anagram-app:latest
